In [1]:
import os
import requests
import zipfile
import io

import pandas as pd

In [2]:
data_path_tsv = "data/mq_variants_intensity.tsv"

# May take a while to download
if not os.path.exists(data_path_tsv):
    os.makedirs("data", exist_ok=True)
    r = requests.post(
        "https://proteomics2.ucsd.edu/ProteoSAFe/DownloadResult?view=mq_variants_intensity&task=a19fe3be4bd84d4a80e58d64e14ba1dd",
        stream=True,
    )
    r.raise_for_status()
    with zipfile.ZipFile(io.BytesIO(r.content)) as z:
        for zipinfo in z.infolist():
            if zipinfo.filename.endswith(".tsv"):
                zipinfo.filename = "mq_variants_intensity.tsv"
            z.extract(zipinfo, "data")

In [3]:
df = pd.read_csv(data_path_tsv, sep="\t", nrows=10)

In [4]:
df.head()

,rowid,ccms_row_id,Variant,Variant ID,Unmod variant,Total,Total- Unmodified sequence,Variants- Unmodified sequence,Proteins,Mass,...,_dyn_#Baricitinib 300nM.Tech replicate 1 of 1,_dyn_#Baricitinib 300nM.Tech replicate 1 of 1_unmod,_dyn_#Baricitinib 30nM.Tech replicate 1 of 1,_dyn_#Baricitinib 30nM.Tech replicate 1 of 1_unmod,_dyn_#Baricitinib 3nM.Tech replicate 1 of 1,_dyn_#Baricitinib 3nM.Tech replicate 1 of 1_unmod,_dyn_#Baricitinib DMSO.Tech replicate 1 of 1,_dyn_#Baricitinib DMSO.Tech replicate 1 of 1_unmod,_dyn_#Baricitinib PDPD.Tech replicate 1 of 1,_dyn_#Baricitinib PDPD.Tech replicate 1 of 1_unmod
0,1,1,.IITHPNFNGNTLDNDIM+15.995LIK.,37658,.IITHPNFNGNTLDNDIMLIK.,11683,20735,81,TRYP_PIG,2299.2,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2,2,.VADPDHDHTGFLTEYVATR.,93378,.VADPDHDHTGFLTEYVATR.,11372,15019,62,sp|P28482-2|MK01_HUMAN;sp|P28482|MK01_HUMAN,2144.0,...,"182,810,000","182,810,000","296,340,000","296,340,000","272,890,000","272,890,000","254,860,000","254,860,000","70,792,000","70,792,000"
2,3,3,.LGEHNIDVLEGNEQFINAAK.,50733,.LGEHNIDVLEGNEQFINAAK.,8878,23098,134,TRYP_PIG,2211.1,...,"152,910,000","152,910,000","313,690,000","313,690,000","187,600,000","187,600,000","313,290,000","313,290,000","204,790,000","204,790,000"
3,4,4,.FRHENIIGINDIIR.,25741,.FRHENIIGINDIIR.,8720,12619,33,sp|P28482-2|MK01_HUMAN;sp|P28482|MK01_HUMAN,1709.9,...,"115,160,000","115,160,000","223,460,000","223,460,000","182,890,000","182,890,000","236,530,000","236,530,000","97,725,000","97,725,000"
4,5,5,.ESESTAGSFSLSVR.,21292,.ESESTAGSFSLSVR.,7995,8328,7,sp|P06239-2|LCK_HUMAN;sp|P06239-3|LCK_HUMAN;sp...,1456.7,...,"19,220,000","19,220,000","11,216,000","11,216,000","12,721,000","12,721,000","12,835,000","12,835,000","8,137,600","8,137,600"

In [5]:
data_path_csv = "data/mq_variants_intensity.csv"
df.to_csv(data_path_csv, index=False)

In [6]:
df = pd.read_csv(data_path_csv)
df.head()

,rowid,ccms_row_id,Variant,Variant ID,Unmod variant,Total,Total- Unmodified sequence,Variants- Unmodified sequence,Proteins,Mass,...,_dyn_#Baricitinib 300nM.Tech replicate 1 of 1,_dyn_#Baricitinib 300nM.Tech replicate 1 of 1_unmod,_dyn_#Baricitinib 30nM.Tech replicate 1 of 1,_dyn_#Baricitinib 30nM.Tech replicate 1 of 1_unmod,_dyn_#Baricitinib 3nM.Tech replicate 1 of 1,_dyn_#Baricitinib 3nM.Tech replicate 1 of 1_unmod,_dyn_#Baricitinib DMSO.Tech replicate 1 of 1,_dyn_#Baricitinib DMSO.Tech replicate 1 of 1_unmod,_dyn_#Baricitinib PDPD.Tech replicate 1 of 1,_dyn_#Baricitinib PDPD.Tech replicate 1 of 1_unmod
0,1,1,.IITHPNFNGNTLDNDIM+15.995LIK.,37658,.IITHPNFNGNTLDNDIMLIK.,11683,20735,81,TRYP_PIG,2299.2,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2,2,.VADPDHDHTGFLTEYVATR.,93378,.VADPDHDHTGFLTEYVATR.,11372,15019,62,sp|P28482-2|MK01_HUMAN;sp|P28482|MK01_HUMAN,2144.0,...,"182,810,000","182,810,000","296,340,000","296,340,000","272,890,000","272,890,000","254,860,000","254,860,000","70,792,000","70,792,000"
2,3,3,.LGEHNIDVLEGNEQFINAAK.,50733,.LGEHNIDVLEGNEQFINAAK.,8878,23098,134,TRYP_PIG,2211.1,...,"152,910,000","152,910,000","313,690,000","313,690,000","187,600,000","187,600,000","313,290,000","313,290,000","204,790,000","204,790,000"
3,4,4,.FRHENIIGINDIIR.,25741,.FRHENIIGINDIIR.,8720,12619,33,sp|P28482-2|MK01_HUMAN;sp|P28482|MK01_HUMAN,1709.9,...,"115,160,000","115,160,000","223,460,000","223,460,000","182,890,000","182,890,000","236,530,000","236,530,000","97,725,000","97,725,000"
4,5,5,.ESESTAGSFSLSVR.,21292,.ESESTAGSFSLSVR.,7995,8328,7,sp|P06239-2|LCK_HUMAN;sp|P06239-3|LCK_HUMAN;sp...,1456.7,...,"19,220,000","19,220,000","11,216,000","11,216,000","12,721,000","12,721,000","12,835,000","12,835,000","8,137,600","8,137,600"